import type { Metadata } from 'next';
import { Merriweather, Lato } from 'next/font/google';
import './globals.css';
import Header from './shared/components/header';
import Providers from './providers';
import { isAuthenticated } from './shared/utils/cookies';

const merriweather = Merriweather({
  subsets: ['latin'],
  variable: '--font-merriweather',
  weight: ['300', '400', '700', '900'],
});

const lato = Lato({
  subsets: ['latin'],
  variable: '--font-lato',
  weight: ['300', '400', '700', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isAuthed = await isAuthenticated();

  return (
    <html lang="en">
      <body className={`${merriweather.variable} ${lato.variable}`}>
        <Providers authenticated={isAuthed}>
          <Header />
          <main className="">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
