import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Providers from "./providers";
import authenticated from "./auth/authenticated";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isAuthenticated = await authenticated();

  return (
    <html lang="en">
      <body>
        <Providers authenticated={isAuthenticated}>
          <Header />
          <main className="">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
