import type { Metadata } from "next";
import { Merriweather, Lato } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Providers from "./providers";
import authenticated from "./auth/authenticated";

const merriweather = Merriweather({
    subsets: ["latin"],
    variable: "--font-merriweather",
    weight: ["300", "400", "700", "900"],
  });
  
  const lato = Lato({
    subsets: ["latin"],
    variable: "--font-lato",
    weight: ["300", "400", "700", "900"],
  });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isAuthenticated = await authenticated();

  return (
    <html lang="en">
      <body className={`${merriweather.variable} ${lato.variable}`}>
        <Providers authenticated={isAuthenticated}>
          <Header />
          <main className="">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
